[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm install && cd apps/api && npx prisma generate && npm run build"]

[start]
cmd = "cd apps/api && node dist/main.js"
