[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npx nest build"

[deploy]
startCommand = "npx prisma migrate deploy; node dist/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
